In [2]:
import sys
print(sys.version)

3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0]

In [3]:
import os
import numpy as np
import pandas as pd
import scipy.sparse as sparse

import stlearn as st
import scanpy as sc
from anndata import AnnData
import anndata

import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk
sc.logging.print_header()
# sc.logging.print_versions()
sc.set_figure_params(facecolor="white", figsize=(8, 8))
sc.settings.verbosity = 3 # errors (0), warnings (1), info (2), hints (3)

sns.set_style("white")

np.random.seed(0)

/home/nikhilmehta/anaconda3/envs/cs690/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
2022-10-01 15:49:36.019360: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-10-01 15:49:36.177020: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-10-01 15:49:36.177061: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2022-10-01 15:49:36.207414: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-10-01 15:49:36.987363: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2022-10-01 15:49:36.987451: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2022-10-01 15:49:36.987459: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.

scanpy==1.9.1 anndata==0.8.0 umap==0.5.3 numpy==1.21.6 scipy==1.9.1 pandas==1.5.0 scikit-learn==1.1.2 statsmodels==0.13.2 python-igraph==0.9.11 louvain==0.7.1 pynndescent==0.5.7

In [4]:
# filtered_h5 = "./cs690Data/Train_filtered_feature_bc_matrix.h5"
# adata = sc.read_10x_h5(filtered_h5)
# display(
#     adata,
#     "Hello",
#     adata.obs, 
#     "=========",
#     adata.var
# )

reading ./cs690Data/Train_filtered_feature_bc_matrix.h5
 (0:00:00)

/home/nikhilmehta/anaconda3/envs/cs690/lib/python3.10/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 3639 × 33538
    var: 'gene_ids', 'feature_types', 'genome'

'Hello'

Empty DataFrame
Columns: []
Index: [AAACAAGTATCTCCCA-1, AAACAATCTACTAGCA-1, AAACACCAATAACTGC-1, AAACAGAGCGACTCCT-1, AAACAGCTTTCAGAAG-1, AAACAGGGTCTATATT-1, AAACAGTGTTCCTGGG-1, AAACATTTCCCGGATT-1, AAACCCGAACGAAATC-1, AAACCGGGTAGGTACC-1, AAACCGTTCGTCCAGG-1, AAACCTAAGCAGCCGG-1, AAACCTCATGAAGTTG-1, AAACGAAGAACATACC-1, AAACGAGACGGTTGAT-1, AAACGGGCGTACGGGT-1, AAACGGTTGCGAACTG-1, AAACTCGGTTCGCAAT-1, AAACTCGTGATATAAG-1, AAACTGCTGGCTCCAA-1, AAACTTAATTGCACGC-1, AAACTTGCAAACGTAT-1, AAAGACATGAAGTTTA-1, AAAGACCCAAGTCGCG-1, AAAGACTGGGCGCTTT-1, AAAGGCCCTATAATAC-1, AAAGGCTACGGACCAT-1, AAAGGCTCTCGCGCCG-1, AAAGGGATGTAGCAAG-1, AAAGGGCAGCTTGAAT-1, AAAGGTAAGCTGTACC-1, AAAGTAGCATTGCTCA-1, AAAGTCACTGATGTAA-1, AAAGTCGACCCTCAGT-1, AAAGTGTGATTTATCT-1, AAAGTTGACTCCCGTA-1, AAATAACCATACGGGA-1, AAATAAGGTAGTGCCC-1, AAATACCTATAAGCAT-1, AAATAGCTTAGACTTT-1, AAATAGGGTGCTATTG-1, AAATCCGATACACGCC-1, AAATCGTGTACCACAA-1, AAATCTAGCCCTGCTA-1, AAATGATTCGATCAGC-1, AAATGCTCGTTACGTT-1, AAATGGCATGTCTTGT-1, AAATGGCCCGTGCCCT-1, AAATGGTCAATGTGCC-1, AAATGTGGGTGCTCCT-1, AAATTAACGGGTAGCT-1, AAATTACACGACTCTG-1, AAATTACCTATCGATG-1, AAATTGATAGTCCTTT-1, AAATTGCGGCGGTTCT-1, AAATTTACCGAAATCC-1, AAATTTGCGGGTGTGG-1, AACAACTGGTAGTTGC-1, AACAATACATTGTCGA-1, AACAATTACTCTACGC-1, AACACACGCTCGCCGC-1, AACACGACTGTACTGA-1, AACACGAGACGCGGCC-1, AACACGCGGCCGCGAA-1, AACAGCTGTGTGGCAA-1, AACAGGAAATCGAATA-1, AACAGGATGGGCCGCG-1, AACAGGTAGTATGGAT-1, AACATATCAACTGGTG-1, AACATCGATACGTCTA-1, AACATTGAAGTTGATC-1, AACATTGGTCAGCCGT-1, AACATTGTGACTCGAG-1, AACCAAGACTTCTCTG-1, AACCAGTATCACTCTT-1, AACCATAGGGTTGAAC-1, AACCATGGGATCGCTA-1, AACCCAGAGACGGAGA-1, AACCCATCCCATGATC-1, AACCCGACAACCCGTG-1, AACCCGAGCAGAATCG-1, AACCCTACTGTCAATA-1, AACCCTGGTGGAACCA-1, AACCGAGCTTGGTCAT-1, AACCGCTAAGGGATGC-1, AACCGTTGTGTTTGCT-1, AACCTAAAGCCGTCCG-1, AACCTCGCTTTAGCCC-1, AACCTTTAAATACGGT-1, AACCTTTACGACGTCT-1, AACGAAAGTCGTCCCA-1, AACGATAATGCCGTAG-1, AACGATAGAAGGGCCG-1, AACGATATGTCAACTG-1, AACGCATGATCTGGGT-1, AACGCGACCTTGGGCG-1, AACGCGGTCTCCAGCC-1, AACGCTGTTGCTGAAA-1, AACGGACGTACGTATA-1, AACGGCCATCTCCGGT-1, ...]

[3639 rows x 0 columns]

'========='

                    gene_ids    feature_types  genome
MIR1302-2HG  ENSG00000243485  Gene Expression  GRCh38
FAM138A      ENSG00000237613  Gene Expression  GRCh38
OR4F5        ENSG00000186092  Gene Expression  GRCh38
AL627309.1   ENSG00000238009  Gene Expression  GRCh38
AL627309.3   ENSG00000239945  Gene Expression  GRCh38
...                      ...              ...     ...
AC233755.2   ENSG00000277856  Gene Expression  GRCh38
AC233755.1   ENSG00000275063  Gene Expression  GRCh38
AC240274.1   ENSG00000271254  Gene Expression  GRCh38
AC213203.1   ENSG00000277475  Gene Expression  GRCh38
FAM231C      ENSG00000268674  Gene Expression  GRCh38

[33538 rows x 3 columns]

In [5]:
# st.Read10X("./cs690Data/",count_file="Train_filtered_feature_bc_matrix.h5")

In [6]:
# st.pp.filter_genes(adata,min_cells=2)
# st.pp.normalize_total(adata)
# st.pp.log1p(adata)

# TILE_PATH = "/tmp/tiles"

# # pre-processing for spot image
# st.pp.tiling(adata, TILE_PATH)

# # this step uses deep learning model to extract high-level features from tile images
# # may need few minutes to be completed
# st.pp.extract_feature(adata)

# # # run PCA for gene expression adata
# st.em.run_pca(adata,n_comps=30)


# data_SME = adata.copy()
# # # apply stSME to normalise log transformed adata
# st.spatial.SME.SME_normalize(data_SME, use_data="raw")
# data_SME.X = data_SME.obsm['raw_SME_normalized']
# st.pp.scale(data_SME)
# st.em.run_pca(data_SME,n_comps=30)

# # K-means clustering on stSME normalised PCA
# st.tl.clustering.kmeans(data_SME,n_clusters=8, use_data="X_pca", key_added="X_pca_kmeans")
# st.pl.cluster_plot(data_SME, use_label="X_pca_kmeans")


# import pandas as pd
# df = pd.DataFrame(data_SME.obs['X_pca_kmeans'])
# # df = pd.DataFrame(data_SME.obs['louvain'])
# df.to_csv("/content/drive/MyDrive/CS690-Assignment1-Task1/output/CSV.csv")


# list_2 = []
# for x in range(3639):
#   list_2.append(int(df.iloc[x,0]))
# # len(list_2)
# print(list2)
# # from sk.metrics.cluster import adjusted_rand_score
# # score = adjusted_rand_score(list_1,list_2)

In [38]:
path = "./cs690Data/"
adata = st.Read10X(path,count_file="Train_filtered_feature_bc_matrix.h5")
# adata = anndata.read_hdf("./cs690Data/Train_filtered_feature_bc_matrix.h5", "matrix")
display(
    adata, 
    adata.obs, 
    adata.var,
    adata.uns,
    "UNS",
    adata.uns["spatial"],
    "OBSM",
    adata.obsm["spatial"]
)

reading cs690Data/Train_filtered_feature_bc_matrix.h5
 (0:00:00)

/home/nikhilmehta/anaconda3/envs/cs690/lib/python3.10/site-packages/anndata/_core/anndata.py:1830: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

AnnData object with n_obs × n_vars = 3639 × 33538
    obs: 'in_tissue', 'array_row', 'array_col', 'imagecol', 'imagerow'
    var: 'gene_ids', 'feature_types', 'genome'
    uns: 'spatial'
    obsm: 'spatial'

                    in_tissue  array_row  array_col     imagecol     imagerow
AAACAAGTATCTCCCA-1          1         50        102  1468.796865  1270.327020
AAACAATCTACTAGCA-1          1          3         43   865.436535   421.092105
AAACACCAATAACTGC-1          1         59         19   610.261020  1425.892575
AAACAGAGCGACTCCT-1          1         14         94  1390.789065   622.712265
AAACAGCTTTCAGAAG-1          1         43          9   509.000895  1137.563745
...                       ...        ...        ...          ...          ...
TTGTTTCACATCCAGG-1          1         58         42   848.034795  1409.540940
TTGTTTCATTAGTCTA-1          1         60         30   723.822375  1444.644450
TTGTTTCCATACAACT-1          1         45         27   694.719465  1174.767465
TTGTTTGTATTACACG-1          1         73         41   835.733565  1679.117895
TTGTTTGTGTAAATTC-1          1          7         51   947.644755   493.699365

[3639 rows x 5 columns]

                    gene_ids    feature_types  genome
MIR1302-2HG  ENSG00000243485  Gene Expression  GRCh38
FAM138A      ENSG00000237613  Gene Expression  GRCh38
OR4F5        ENSG00000186092  Gene Expression  GRCh38
AL627309.1   ENSG00000238009  Gene Expression  GRCh38
AL627309.3   ENSG00000239945  Gene Expression  GRCh38
...                      ...              ...     ...
AC233755.2   ENSG00000277856  Gene Expression  GRCh38
AC233755.1   ENSG00000275063  Gene Expression  GRCh38
AC240274.1   ENSG00000271254  Gene Expression  GRCh38
AC213203.1   ENSG00000277475  Gene Expression  GRCh38
FAM231C      ENSG00000268674  Gene Expression  GRCh38

[33538 rows x 3 columns]

OverloadedDict, wrapping:
	OrderedDict([('spatial', {'151673': {'images': {'hires': array([[[0.68235296, 0.69803923, 0.69411767],
        [0.68235296, 0.69411767, 0.6901961 ],
        [0.6784314 , 0.69803923, 0.6901961 ],
        ...,
        [0.6784314 , 0.6901961 , 0.6901961 ],
        [0.6745098 , 0.69411767, 0.6901961 ],
        [0.68235296, 0.69803923, 0.6901961 ]],

       [[0.68235296, 0.69411767, 0.6901961 ],
        [0.68235296, 0.69803923, 0.6862745 ],
        [0.68235296, 0.69411767, 0.6862745 ],
        ...,
        [0.6745098 , 0.6862745 , 0.6862745 ],
        [0.6784314 , 0.69411767, 0.6901961 ],
        [0.68235296, 0.69411767, 0.6901961 ]],

       [[0.6862745 , 0.69411767, 0.6862745 ],
        [0.68235296, 0.69803923, 0.69411767],
        [0.6784314 , 0.69411767, 0.6862745 ],
        ...,
        [0.6784314 , 0.69411767, 0.6901961 ],
        [0.6745098 , 0.6862745 , 0.68235296],
        [0.6784314 , 0.69411767, 0.69411767]],

       ...,

       [[0.6745098 , 0.69411767, 0.68235296],
        [0.6784314 , 0.69411767, 0.6862745 ],
        [0.6745098 , 0.69411767, 0.6862745 ],
        ...,
        [0.68235296, 0.69803923, 0.6901961 ],
        [0.68235296, 0.69803923, 0.69411767],
        [0.6784314 , 0.7019608 , 0.6901961 ]],

       [[0.6784314 , 0.6901961 , 0.68235296],
        [0.6784314 , 0.69411767, 0.68235296],
        [0.68235296, 0.69803923, 0.6862745 ],
        ...,
        [0.6784314 , 0.69803923, 0.6901961 ],
        [0.6745098 , 0.69411767, 0.6901961 ],
        [0.68235296, 0.69803923, 0.6901961 ]],

       [[0.6745098 , 0.69411767, 0.6784314 ],
        [0.6784314 , 0.69803923, 0.6862745 ],
        [0.6745098 , 0.69411767, 0.6862745 ],
        ...,
        [0.6784314 , 0.7019608 , 0.6901961 ],
        [0.68235296, 0.69803923, 0.6901961 ],
        [0.68235296, 0.69803923, 0.6901961 ]]], dtype=float32), 'lowres': array([[[0.68235296, 0.69803923, 0.69411767],
        [0.68235296, 0.69411767, 0.6901961 ],
        [0.6784314 , 0.69803923, 0.6901961 ],
        ...,
        [0.6784314 , 0.6901961 , 0.6901961 ],
        [0.6745098 , 0.69411767, 0.6901961 ],
        [0.68235296, 0.69803923, 0.6901961 ]],

       [[0.68235296, 0.69411767, 0.6901961 ],
        [0.68235296, 0.69803923, 0.6862745 ],
        [0.68235296, 0.69411767, 0.6862745 ],
        ...,
        [0.6745098 , 0.6862745 , 0.6862745 ],
        [0.6784314 , 0.69411767, 0.6901961 ],
        [0.68235296, 0.69411767, 0.6901961 ]],

       [[0.6862745 , 0.69411767, 0.6862745 ],
        [0.68235296, 0.69803923, 0.69411767],
        [0.6784314 , 0.69411767, 0.6862745 ],
        ...,
        [0.6784314 , 0.69411767, 0.6901961 ],
        [0.6745098 , 0.6862745 , 0.68235296],
        [0.6784314 , 0.69411767, 0.69411767]],

       ...,

       [[0.6745098 , 0.69411767, 0.68235296],
        [0.6784314 , 0.69411767, 0.6862745 ],
        [0.6745098 , 0.69411767, 0.6862745 ],
        ...,
        [0.68235296, 0.69803923, 0.6901961 ],
        [0.68235296, 0.69803923, 0.69411767],
        [0.6784314 , 0.7019608 , 0.6901961 ]],

       [[0.6784314 , 0.6901961 , 0.68235296],
        [0.6784314 , 0.69411767, 0.68235296],
        [0.68235296, 0.69803923, 0.6862745 ],
        ...,
        [0.6784314 , 0.69803923, 0.6901961 ],
        [0.6745098 , 0.69411767, 0.6901961 ],
        [0.68235296, 0.69803923, 0.6901961 ]],

       [[0.6745098 , 0.69411767, 0.6784314 ],
        [0.6784314 , 0.69803923, 0.6862745 ],
        [0.6745098 , 0.69411767, 0.6862745 ],
        ...,
        [0.6784314 , 0.7019608 , 0.6901961 ],
        [0.68235296, 0.69803923, 0.6901961 ],
        [0.68235296, 0.69803923, 0.6901961 ]]], dtype=float32)}, 'scalefactors': {'spot_diameter_fullres': 96.40082438014726, 'tissue_hires_scalef': 0.150015, 'fiducial_diameter_fullres': 144.6012365702209, 'tissue_lowres_scalef': 0.045004502}, 'metadata': {'chemistry_description': 'custom', 'software_version': '4509.5.5'}, 'use_quality': 'hires'}})])
With overloaded keys:
	['neighbors'].

'UNS'

{'151673': {'images': {'hires': array([[[0.68235296, 0.69803923, 0.69411767],
           [0.68235296, 0.69411767, 0.6901961 ],
           [0.6784314 , 0.69803923, 0.6901961 ],
           ...,
           [0.6784314 , 0.6901961 , 0.6901961 ],
           [0.6745098 , 0.69411767, 0.6901961 ],
           [0.68235296, 0.69803923, 0.6901961 ]],

          [[0.68235296, 0.69411767, 0.6901961 ],
           [0.68235296, 0.69803923, 0.6862745 ],
           [0.68235296, 0.69411767, 0.6862745 ],
           ...,
           [0.6745098 , 0.6862745 , 0.6862745 ],
           [0.6784314 , 0.69411767, 0.6901961 ],
           [0.68235296, 0.69411767, 0.6901961 ]],

          [[0.6862745 , 0.69411767, 0.6862745 ],
           [0.68235296, 0.69803923, 0.69411767],
           [0.6784314 , 0.69411767, 0.6862745 ],
           ...,
           [0.6784314 , 0.69411767, 0.6901961 ],
           [0.6745098 , 0.6862745 , 0.68235296],
           [0.6784314 , 0.69411767, 0.69411767]],

          ...,

          [[0.6745098 , 0.69411767, 0.68235296],
           [0.6784314 , 0.69411767, 0.6862745 ],
           [0.6745098 , 0.69411767, 0.6862745 ],
           ...,
           [0.68235296, 0.69803923, 0.6901961 ],
           [0.68235296, 0.69803923, 0.69411767],
           [0.6784314 , 0.7019608 , 0.6901961 ]],

          [[0.6784314 , 0.6901961 , 0.68235296],
           [0.6784314 , 0.69411767, 0.68235296],
           [0.68235296, 0.69803923, 0.6862745 ],
           ...,
           [0.6784314 , 0.69803923, 0.6901961 ],
           [0.6745098 , 0.69411767, 0.6901961 ],
           [0.68235296, 0.69803923, 0.6901961 ]],

          [[0.6745098 , 0.69411767, 0.6784314 ],
           [0.6784314 , 0.69803923, 0.6862745 ],
           [0.6745098 , 0.69411767, 0.6862745 ],
           ...,
           [0.6784314 , 0.7019608 , 0.6901961 ],
           [0.68235296, 0.69803923, 0.6901961 ],
           [0.68235296, 0.69803923, 0.6901961 ]]], dtype=float32),
   'lowres': array([[[0.68235296, 0.69803923, 0.69411767],
           [0.68235296, 0.69411767, 0.6901961 ],
           [0.6784314 , 0.69803923, 0.6901961 ],
           ...,
           [0.6784314 , 0.6901961 , 0.6901961 ],
           [0.6745098 , 0.69411767, 0.6901961 ],
           [0.68235296, 0.69803923, 0.6901961 ]],

          [[0.68235296, 0.69411767, 0.6901961 ],
           [0.68235296, 0.69803923, 0.6862745 ],
           [0.68235296, 0.69411767, 0.6862745 ],
           ...,
           [0.6745098 , 0.6862745 , 0.6862745 ],
           [0.6784314 , 0.69411767, 0.6901961 ],
           [0.68235296, 0.69411767, 0.6901961 ]],

          [[0.6862745 , 0.69411767, 0.6862745 ],
           [0.68235296, 0.69803923, 0.69411767],
           [0.6784314 , 0.69411767, 0.6862745 ],
           ...,
           [0.6784314 , 0.69411767, 0.6901961 ],
           [0.6745098 , 0.6862745 , 0.68235296],
           [0.6784314 , 0.69411767, 0.69411767]],

          ...,

          [[0.6745098 , 0.69411767, 0.68235296],
           [0.6784314 , 0.69411767, 0.6862745 ],
           [0.6745098 , 0.69411767, 0.6862745 ],
           ...,
           [0.68235296, 0.69803923, 0.6901961 ],
           [0.68235296, 0.69803923, 0.69411767],
           [0.6784314 , 0.7019608 , 0.6901961 ]],

          [[0.6784314 , 0.6901961 , 0.68235296],
           [0.6784314 , 0.69411767, 0.68235296],
           [0.68235296, 0.69803923, 0.6862745 ],
           ...,
           [0.6784314 , 0.69803923, 0.6901961 ],
           [0.6745098 , 0.69411767, 0.6901961 ],
           [0.68235296, 0.69803923, 0.6901961 ]],

          [[0.6745098 , 0.69411767, 0.6784314 ],
           [0.6784314 , 0.69803923, 0.6862745 ],
           [0.6745098 , 0.69411767, 0.6862745 ],
           ...,
           [0.6784314 , 0.7019608 , 0.6901961 ],
           [0.68235296, 0.69803923, 0.6901961 ],
           [0.68235296, 0.69803923, 0.6901961 ]]], dtype=float32)},
  'scalefactors': {'spot_diameter_fullres': 96.40082438014726,
   'tissue_hires_scalef': 0.150015,
   'fiducial_diameter_fullres': 144.6012365702209,
   'tissue_lowres_scalef': 0.045004502},
  'metadata': {'chemistry_description': 'custom',
   'software_version': '4509.5.5'},
  'use_quality': 'hires'}}

'OBSM'

array([[ 9791,  8468],
       [ 5769,  2807],
       [ 4068,  9505],
       ...,
       [ 4631,  7831],
       [ 5571, 11193],
       [ 6317,  3291]])

In [28]:
# print(adata.X)
# print(adata.Y)
print(adata.obsm["spatial"])
print(f"Matrix sparsity: {adata.X.nnz} filled elements "
      f"({adata.X.nnz/adata.X.shape[0]/adata.X.shape[1]:0.2f}) "
      f"out of {adata.X.shape[0]*adata.X.shape[1]}\n"
      f"max: {np.amax(adata.X.data)}, min: {np.amin(adata.X.data)}")

[[ 9791  8468]
 [ 5769  2807]
 [ 4068  9505]
 ...
 [ 4631  7831]
 [ 5571 11193]
 [ 6317  3291]]
Matrix sparsity: 8021506 filled elements (0.07) out of 122044782
max: 610.0, min: 1.0